### ISSUE TITLE
Comunicazione Server - Mobile Android

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#10]
Cercare di far comunicare il server con uno smartphone Android che visualizzerà i messaggi ricevuti

**Comment by PepponeFX** [comment]
Il client funziona su mobile Android (riceve i messaggi). 
Per farlo funzionare, ho usato html5 su mobile immaginando di poter realizzare un'app installabile che sia anche cross platform quindi tecnicamente dovrebbe funzionare anche su iOS.

**Comment by PepponeFX** [comment]
Non funziona con App

**Comment by lanubile** [comment]
Il funzionamento su IoS andrebbe testato e non dato per scontato.

**Comment by PepponeFX** [comment]
Non ho uno smartphone IoS però se riusciamo a procurarlo, potremmo anche testarlo

**Comment by PepponeFX** [comment]
In attesa di verifica su IoS
