### ISSUE TITLE
Manca il pulsante Indietro in tutte le pagine

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/scriba#100]
Poiché non si può usare il Back del browser, l'unico modo di andare indietro è da menu

**Comment by lanubile** [comment]
@PepponeFX dice che il codice del pulsante indietro esisteva ma ora non è più visualizzato

**Comment by fastluca** [comment]
@PepponeFX @lanubile il pulsante indietro nella precedente versione dove compariva? Al posto del menu come mostrato nell'imamgine sotto giusto?
![immagine](https://user-images.githubusercontent.com/11456897/29973165-d8ee5442-8f2e-11e7-88c2-3c55a91892f6.png)

**Comment by PepponeFX** [comment]
Si, esatto

Il 01 set 2017 16:02, "Gianluca Colaianni" <notifications@github.com> ha
scritto:

**Comment by fastluca** [comment]
@PepponeFX la pull request #104 risolve questa issue.
