### ISSUE TITLE
Non arrivano le domande allo speaker

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/scriba#102]

**Comment by fastluca** [comment]
@PepponeFX @lanubile riuscite a dettagliare meglio questa issue? Non ho ben chiaro il problema.
Grazie

**Comment by PepponeFX** [comment]
@fastluca Una volta avviato l'intervento, chi ascolta può cliccare l'iconcina della mano per inviare un messaggio ai presenti nella stanza (es. fare una domanda). Il messaggio non viene ricevuto (risulta che qualcuno ha inviato il messaggio ma il testo non arriva)

**Comment by fastluca** [comment]
@PepponeFX mi aiuteresti a riprodurlo? Ho individuato la componente che se ne occupa, ma non mi sono chiari i passaggi per arrivarci.
Grazie

**Comment by PepponeFX** [comment]
Apri due finestre (oppure una finestra e uno smartphone): una deve servire per lo speaker e una per l'ascoltatore; come speaker avvia l'intervento e il riconoscimento; come ascoltatore inizia l'ascolto; come ascoltatore invia un messaggio usando l'icona della mano.

**Comment by fastluca** [comment]
@PepponeFX è questo il risultato atteso, giusto? (lato speaker)
![immagine](https://user-images.githubusercontent.com/11456897/29976063-0920e95e-8f39-11e7-9ed9-22f54abef6ed.png)

**Comment by PepponeFX** [comment]
@fastluca esatto, anche gli altri ascoltatori connessi dovrebbero visualizzare l'intervento

**Comment by fastluca** [comment]
@PepponeFX la pull request #105 risolve questa issue.
