### ISSUE TITLE
Effettuare Test sulle GWAPI

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#11]
Cerchiamo di capire un pattern per cui si interrompe il riconoscimento pur restando attivo il servizio (l’icona di REC è attiva)

**Comment by PepponeFX** [comment]
Ancora non ho capito perchè, sembra non produrre errori, semplicemente ogni tanto sembrerebbe andare in sovraccarico.
Per ora ho messo un restart del riconoscimento quando questo non viene interrotto dall'utente.

**Comment by PepponeFX** [comment]
A parte il problema dello stop automatico risolto (solo in parte) con un restart (vedi commento sopra), sembra davvero andare in crash quando ci sono rumori forti o troppo vocio di fondo che entra nel microfono, questo problema è facilmente risolvibile (in linea teorica) con un dispositivo di cattura audio adeguato.

**Comment by rodenic** [comment]
Nei sistemi audio esistono circuiti o software che attivano l'input audio solo quando il rapporto segnale rumore è sopra un certo valore e lo mettono in mute negli altri casi. Si chiamano NOISE GATE, SQUELCH. Potrebbe anche essere inglobato nella app.

**Comment by lanubile** [comment]
@rodenic testerà da casa con un noise gate all'indirizzo http://collab.di.uniba.it/~iaffaldano/serverNode/public/speakerSide.html

**Comment by PepponeFX** [comment]
Ho inserito come messaggi in console le attivazioni di ciascun evento per verificare cosa succede esattamente durante il riconoscimento. 
Ho messo a commento la comunicazione con il server node in modo che Roberto possa testare da casa tutto quello che desidera senza errori in console (al link nel commento precedente).

**Comment by lanubile** [comment]
@rodenic @PepponeFX Abbiamo notizie sul test che Roberto doveva fare con il noise gate?

**Comment by PepponeFX** [comment]
Se gli speaker si scambiano il microfono (cambio voce) non ci sono problemi; se c'è silenzio di fondo non si hanno problemi. Pare che il problema sorga se si accavallano le voci.

**Comment by lanubile** [comment]
Le GWAPI vanno bene se si tratta di fare una demo ma risultano inaffidabili per un uso in un meeting reale a causa del disturbo dovuto alla sovrapposizione di voci, cosa possibile anche in un workshop
