### ISSUE TITLE
Predisporre interfaccia Web con IONIC

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#13]
Integrare React nel progetto e iniziare a predisporre l'interfaccia per un "Intervento"

**Comment by lanubile** [comment]
Perché haio classificato questo come Done se stai cambiando idea su react?

**Comment by PepponeFX** [comment]
Ho modificato la scelta della libreria di View riaprendo l'Issue, scrivendo il motivo della deviazione e spostando l'issue sui Done. Inoltre ho modificato il nome di questo Issue sostituendo "React" con "Angular e Bootstrap"

**Comment by lanubile** [comment]
quale versione di angular? spero la 2

**Comment by PepponeFX** [comment]
Ho iniziato con la 1 perchè la 2 è basata su Typescript, ho paura di avere lo stesso problema di React.
Sono però consapevole che la versione 1 è destinata a lasciare il posto completamente alla 2 e molti sviluppatori dovranno effettuare una migrazione alla nuova versione. Per questo motivo vedrò di realizzare un nuovo progetto con la versione 2 di AngularJS che comprenderà non più Bootstrap come framework grafico ma Ionic che sta rimpiazzando il primo.
Entro il prossimo incontro deciderò in maniera definitiva tutto quello che mi serve per iniziare a creare il progetto definitivo e lavorare sulle User Story.

**Comment by lanubile** [comment]
Va testato anche con iOS

**Comment by lanubile** [comment]
Va verificato che è sensibile alla rotazione

**Comment by PepponeFX** [comment]
Per il deployment su IOS ho bisogno di Xcode che funziona solo su IOS. Volendo potrei utilizzare una macchina virtuale su cui installare una versione "poco originale" di IOS e su cui potrei emulare il dispositivo. Però non potrei testarlo sul dispositivo fisico e non vorrei rischiare il ban dell'account development di ISF usandolo su una versione "poco originale" di IOS.

**Comment by flippolis** [comment]
Ti porto un Mac Mini.

**Comment by PepponeFX** [comment]
L'applicazione parte e funziona, necessita però di un restyling (Creata nuova issue come "enhancement")
