### ISSUE TITLE
Creare sessioni di un evento

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#17]
Come organizzatore di eventi vorrei programmare delle Sessioni per un evento
Sessione:
- Titolo: Titolo della singola sessione dell’evento
- Data: Data della sessione dell’evento, coincide con la data dell’evento solo se si tiene in un solo giorno
- Ora: Ora in cui avrà inizio la sessione

**Comment by PepponeFX** [comment]
Ogni sessione viene creata, il server si occupa di inserire alla creazione un intervento con gli stessi dati della sessione (Serve nel caso in cui si volesse creare rapidamente una sessione single intervent. Altrimenti l'utente si occuperà di modificare i dati delle sessioni e degli interventi)

**Comment by PepponeFX** [comment]
Dovrebbe avere ORA di INIZIO e ora di FINE

**Comment by PepponeFX** [comment]
- Le sessioni possono essere aggiunte in qualsiasi momento
- Le sessioni sono vincolate solo dalla durata dell'evento e dalle sessioni aggiunte in precedenza
- Tutte le sessioni possono essere eliminate

**Comment by PepponeFX** [comment]
Si dovrebbero permettere SESSIONI PARALLELE

**Comment by flippolis** [comment]
Propongo di conservare il controllo sulla sovrapposizione delle sessioni, ma avvisare l'utente e chiedere conferma sulla corretta schedulazione. In futuro una terza opzione potrebbe essere quella di permettere la schedulazione della sessione shiftandola alla prima fascia oraria disponibile (da ragionarci su).
