### ISSUE TITLE
Scelta del Servizio ASR/STT

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#2]
Si vuole selezionare un servizio di Automatic Speech Recognition per lo Speech-to-Text da utilizzare come core per la trascrizione del parlato dello/degli speaker.
La selezione sarà effettuata in 3 fasi successive:
1. Ricerca: saranno ricercati tutti i servizi che forniscono soluzioni all'esigenza
2. Selezione: saranno selezionati solo quei servizi che si adattano ai bisogni del sistema
3. Adozione: saranno utilizzati e confrontati i servizi scelti

**Comment by lanubile** [comment]
Candidati Eletti:
- Google Cloud Services --> Servono servizi Cloud a Pagamento
- Nuance Dragon SDK --> SOLO EMERALD
- Google Web Speech API --> OK
