### ISSUE TITLE
Dettagliare terminologia utilizzata

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/scriba#3]
Come chiamare 
- lo speaker: relatore?
- il listener: uditore? (bleah)

**Comment by rodenic** [comment]
Speaker
Listener

!!!
Il 24/Mag/2016 18:42, "lanubile" notifications@github.com ha scritto:

**Comment by PepponeFX** [comment]
La scelta dei termini da utilizzare è inclusa nel file "Terminologia" di cui allego il link e che è presente nella cartella Drive condivisa.

Terminologia: https://docs.google.com/document/d/1Gn2fYJXpAZTfNP1R555RrV2uJeeiMq_KSYI7uRO4z_g/edit?usp=sharing

**Comment by PepponeFX** [comment]
Approvato il file allegato al commento precedente
