### ISSUE TITLE
Creare profilo (Sign in)

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#51]

**Comment by lanubile** [comment]
Si entra con il pulsante SIgn in ma si incontra poi la parola Register come titolo e pulsante. Non va bene

**Comment by PepponeFX** [comment]
Uniformati i pulsanti in Italiano

**Comment by PepponeFX** [comment]
Impostare Email Come Obbligatoria

**Comment by PepponeFX** [comment]
Email impostata come obbligatoria, inserito il "conferma password" e migliorato il codice.
