### ISSUE TITLE
Modificare dati del profilo

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#53]

**Comment by lanubile** [comment]
Ci sono pulsanti in lingua mista Salva e Cancel. Non va bene

**Comment by PepponeFX** [comment]
Uniformati i pulsanti in Italiano

**Comment by PepponeFX** [comment]
Porre l'EMAIL OBBLIGATORIA e mostrare l'USERNAME

**Comment by PepponeFX** [comment]
Impostata l'email obbligatoria, l'Username viene visualizzato in testa al form "Il Mio Profilo - Username"
