### ISSUE TITLE
Deployment sul Server

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#61]
Portare il sistema sul server e testare il comportamento

**Comment by flippolis** [comment]
Segnalo
[Node.js and Forever as a Service](https://www.exratione.com/2013/02/nodejs-and-forever-as-a-service-simple-upstart-and-init-scripts-for-ubuntu/)
[foreverjs/forever](https://github.com/foreverjs/forever)

**Comment by lanubile** [comment]
Si potrebbe prendere in considerazione la creazione di un container docker?

**Comment by PepponeFX** [comment]
Sul Server non riesco ad installare le dipendenze. Mi occorrerebbero MongoDB v3.2; NodeJS v6.X; NPM v3.X.
Per il momento non sto riuscendo a trovare una soluzione.

**Comment by flippolis** [comment]
La soluzione che suggerisce il Prof. non è applicabile?

**Comment by flippolis** [comment]
Non conosco le caratteristiche del sistema target, ricordo solo che si tratta di una Debian ma non so che versione. Il repository ufficiale Debian contiene delle versioni obsolete di MongoDB, Node.js e npm. Tuttavia esistono dei repository alternativi per Wheezy o Jessie (Debian 7.x o 8.x) che ti permetterebbero di installare le versioni richieste:

https://docs.npmjs.com/getting-started/installing-node
http://tecadmin.net/install-mongodb-on-ubuntu/#

Ovviamente previa autorizzazione di @lanubile e @bateman. Potresti provare prima su una VirtualBox VM e verificare che l'installazione vada a buon fine.

**Comment by PepponeFX** [comment]
Sto esplorando un po' Docker ma sembra che la connessione ostacoli il suo corretto funzionamento (o sono io che non capisco il problema) Inoltre, non ho capito bene se con Docker è possibile avviare separatamente MongoDB, Server e Client e farli comunque comunicare.

Per quanto riguarda i repository alternativi, ci sto dando un'occhiata

**Comment by bateman** [comment]
il problema e' che il server e' a 32bit, percio' ne' la soluzione con i
repo ne' quella con docker sono percorribili.
ho detto a Peppone di creare una VM con linux server sulla sua macchina per
poi spostarla sul server una volta configurata come ritiene necessario

---

Dr. Fabio Calefato, PhD
University of Bari - Dipartimento Jonico in "Sistemi Giuridici ed Economici"
Via Duomo, 259 - 74123 Taranto - ITALY

home: http://collab.di.uniba.it/fabio
blog:   http://collab.di.uniba.it/blog

_Please, consider submitting to the Social Software Engineering Workshop
(SSE'16) http://sse-ws.github.io/index.html @ FSE
http://www.cs.ucdavis.edu/fse2016/_

2016-07-26 16:22 GMT+02:00 PepponeFX notifications@github.com:

**Comment by PepponeFX** [comment]
Ho recuperato il mio vecchio Laptop su cui ho installato Ubuntu 16.04 LTS a 64bit. Ho installato MongoDB 3.2, NodeJS 6.3.1, NPM 3.10.3, ionic@beta (2.0.0-beta.33) e tutte le dipendenze per il server e per il client. @bateman mi ha assegnato l'IP locale 192.168.0.44 e sto lavorando su quello. Sembra funzionare tutto.

**Comment by PepponeFX** [comment]
Verificare se è possibile l'Hosting da parte di BLUEMIX o AZURE;

**Comment by PepponeFX** [comment]
Verificare se è possibile utilizzare Docker

**Comment by PepponeFX** [comment]
Utilizzare porte assegnate staticamente (o un range di porte)
