### ISSUE TITLE
Automatizzare Docker Containers

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#63]
Creare container su Docker

**Comment by PepponeFX** [comment]
Automatizzare la creazione di container ad ogni committ

**Comment by lanubile** [comment]
La pull request creata e chiusa (78) è relativa a questo issue? Se sì, ci state lavorando ancora?

**Comment by gaetanoziri** [comment]
Ci stiamo ancora lavorando, la pull request #78 non era conforme, ne effettueremo una nuova al termine del lavoro. @PepponeFX @lanubile possiamo spostare questa issue nello stato "In Progress"?

**Comment by lanubile** [comment]
OK, grazie. Sposto io

**Comment by gaetanoziri** [comment]
@PepponeFX la pull request #80 risolve questa issue.

**Comment by lanubile** [comment]
@PepponeFX Quando chiudi una issue passala in Done.

**Comment by PepponeFX** [comment]
@gaetanoziri @fastluca Avete già creato i nuovi container? dove sono? in caso contrario, avete bisogno di indicazioni?

**Comment by gaetanoziri** [comment]
@PepponeFX i comandi per aggiornare i container sono scritti nel [README](https://github.com/collab-uniba/scriba/blob/master/README.md) come indicato nella pull request #80 
Se vuoi posso aggiornarli io.

**Comment by PepponeFX** [comment]
@gaetanoziri se riesci a farlo tu è meglio. Sul server c'è anche un proxy in go in un container separato, andrebbe collegato anche quello agli altri. Se hai bisogno contattami via mail.

**Comment by gaetanoziri** [comment]
@PepponeFX  ho creato i nuovi container, mi resta da collegare il container go proxy. 
`docker run --name goproxy --link ionicserver --link node pepponefx/scriba_proxy go run httpsproxy.go`
il comando che  sto usando è questo, è corretto?

**Comment by PepponeFX** [comment]
docker run --name goproxy --link *nomecontainerionic* pepponefx/scriba_proxy
go run httpsproxy.go

Il 26 ago 2017 13:13, "Gaetano" <notifications@github.com> ha scritto:

@PepponeFX <https://github.com/pepponefx> ho creato i nuovi container, mi
resta da collegare il container go proxy.
docker run --name goproxy --link ionicserver --link node
pepponefx/scriba_proxy go run httpsproxy.go
il comando che sto usando è questo, è corretto?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/collab-uniba/scriba/issues/63#issuecomment-325116136>,
or mute the thread
