### ISSUE TITLE
Scelta View di MVC

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/scriba#7]
Lato “V” di MVC userò **REACT** perchè è molto modulare e rappresenta a quanto dicono in giro il futuro delle view

**Comment by PepponeFX** [comment]
Pur essendo una libreria molto prestante con la gestione del suo DOM virtuale, React offre ottime prestazioni nella sua versione nativa con file JSX che vanno compilati e trasformati in JS dal motore Babel, inoltre per lavorare su browser, è necessario utilizzare la libreria Browserify per simulare un "server" sul browser. Tutto questo porta ad una destrutturazione dei moduli che impedisce una corretta suddivisione delle responsabilità tra essi, inoltre alcune funzionalità previste non sono ancora realizzabili in maniera efficiente poichè Browserify non supporta appieno tali funzionalità.

Per una corretta strutturazione dei moduli, divisione delle responsabilità ecc. si opterà per l'utilizzo di jQuery per il controllo, Bootstrap per l'interfaccia (CSS, Animazioni), AngularJS come framework per la codifica efficace della WebApp nel suo complesso

**Comment by lanubile** [comment]
Ero convinto che AngularJS facesse tutto quello che serve per il frontend di una webapp. Può servire una consulenza di esperti?

**Comment by PepponeFX** [comment]
Non dovrebbe servire, sto riuscendo man mano a far qualcosa di concreto con AngularJS. SI, è un framework completo e perfettamente adatto alle esigenze.

**Comment by PepponeFX** [comment]
In ultima analisi ho scelto di utilizzare il framework IONIC con la sua versione 2 (in beta) che include Cordova (per lo sviluppo di app Ibride - multipiattaforma); Angular 2, jQuery e diversi CSS per l'interfaccia.
