### ISSUE TITLE
Inserire test automatici server

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#75]
automatizzare il test al commit con strumenti come travis.ci

**Comment by fastluca** [comment]
@lanubile, @PepponeFX questo può passare nello stato "In progress". Ci aspettiamo di chiuderlo questa settimana. Grazie.

**Comment by fastluca** [comment]
@PepponeFX, è stata creata la pull request #83 per chiudere questa issue.

**Comment by fastluca** [comment]
@PepponeFX risulta open. Possiamo considerarlo chiuso ed in tal caso chiuderlo qui? Grazie
