### ISSUE TITLE
Ripristinare le dipendenze "rotte" di Ionic

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/scriba#76]
Ionic  --> Angular
Ionic  --> Cordova

**Comment by lanubile** [comment]
Ci state ancora lavorando o state solo attendendo la verifica?

**Comment by fastluca** [comment]
@PepponeFX o @lanubile, questo issue è relativo alla pull request #79 mergiata da @PepponeFX. L'issue può passare nello stato "Done"?

**Comment by PepponeFX** [comment]
Le dipendenze sono state ripristinate, questo può passare in "Done", c'è bisogno ora di ripristinare la visualizzazione dell'interfaccia. Apro una nuova Issue.

**Comment by fastluca** [comment]
@PepponeFX risulta ancora open. Possiamo considerarlo chiuso ed in tal caso chiuderlo qui? Grazie
