### ISSUE TITLE
Deployment su un nuovo server

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/scriba#77]
Ipotesi: MV su data center ReCaS-UNIBA

**Comment by fastluca** [comment]
@lanubile , è possibile procedere con la richiesta per la macchina virtuale sul data center ReCaS-UNIBA? Non abbiamo trovato nessun'altra alternativa. Grazie.

**Comment by lanubile** [comment]
L'issue è stato risolto da Iaffaldano con l'aiuto del personale di Recas. 
Riporto ill dialogo tra @PepponeFX e Recas:

Il giorno 31 luglio 2017 12:32, Giacinto Donvito <giacinto.donvito@ba.infn.it> ha scritto:
ho aggiunto la chiave per entrare nella macchina: 
ssh ubuntu@90.147.102.74

---------------------------------
Il giorno 31 lug 2017, alle ore 12:27, Giuseppe Iaffaldano <pepponefx@gmail.com> ha scritto:

Allego la chiave per l'accesso, per il momento possiamo provare a fare il deploy del server node con il db.

Comandi usati:
docker pull pepponefx/scriba_mongodb
docker run -d --name db pepponefx/scriba_mongodb

docker pull pepponefx/scriba_node_server
docker run -d --name node --link db pepponefx/scriba_node_server node server.js

Vorrei vedere se funzionano questi, in caso positivo procederò a configurare il server Ionic e passarvi i comandi per deployare anche quello.

-----------------------------------------
Il giorno 27 luglio 2017 15:36, Stefano Nicotri <stefano.nicotri@infn.it> ha scritto:
Ciao a tutti,
abbiamo creato una VM per testare i servizi da portare su Mesos (90.147.102.74). Abbiamo installato l'ultima versione di Docker CE e abbiamo aperto le porte 9090, 9091, 9092. Fateci sapere se serve aprirne altre.
Appena ci passate la chiave con cui volete accedere la inseriamo.
Abbiamo bisogno che venga ricreato il sistema da portare su Mesos, con tutti i container che lo compongono. Come possiamo procedere? Potete fornirci le istruzioni dettagliate (i comandi) per l'istanziazione dei docker?

**Comment by lanubile** [comment]
@fastluca leggi con attenzione il dialogo. Testa se funziona il server e se ci sono problemi contatta @PepponeFX .

**Comment by fastluca** [comment]
@gaetanoziri il dockerfile presente sul branch #78 dobbiamo testarlo sul server messo a disposizione. Sopra ci sono i riferimenti. @PepponeFX, per accedere al server abbiamo bisogno della chiave di accesso. Grazie

**Comment by PepponeFX** [comment]
Ho mandato la chiave via mail a @fastluca.

**Comment by lanubile** [comment]
questa issue è ancora da verificare? @PepponeFX

**Comment by PepponeFX** [comment]
Non sono riuscito a creare un apk che possa essere installato. apro un'altra issue (che sarà immediatamente successiva alla #81 e chiudo questa perchè via web funziona tutto.
