### ISSUE TITLE
Ripristino Visualizzazione Interfaccia

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#81]
In seguito al ripristino delle dipendenze è necessario ripristinare la visualizzazione originale delle pagine che risulta al momento inadeguata.

**Comment by fastluca** [comment]
@PepponeFX, se riesci a fornirci qualche screen della vecchia applicazione forse possiamo intervenire anche su questo task. Al momento, dal mio punto di vista, l'unica anomalia è la mancata visualizzazione dei tab superioiri relativi gli eventi (in corso, programmati, ecc) che dovrei aver risolto con una piccola fix. Con la fix il risultato ottenuto è il seguente:
![immagine](https://user-images.githubusercontent.com/11456897/29066839-c247592a-7c30-11e7-9a81-548dabd13fdc.png)
Ti risulta sia coerente con il comportamento della versione precedente? Se mi dai conferma procedo con la commit.
Grazie

**Comment by PepponeFX** [comment]
La visualizzazione dovrebbe essere come su https://90.147.102.74:9090 (Usate Chrome) su tutti i dispositivi indicativamente. Non ho screenshot da mostrarvi

**Comment by fastluca** [comment]
@PepponeFX con la pull request #87 si risolvono i problemi di visualizzaizone dei bottoni, della navigation bar e dei modals che si avevano dopo l'aggiornamento alla versione più recente di ionic.

**Comment by fastluca** [comment]
@lanubile con la pull request #88 per me questo issue è chiuso, almeno che voi non trovate altre incongruenze con il rendering dell'interfaccia client.

**Comment by lanubile** [comment]
@fastluca @gaetanoziri @PepponeFX 
Vorrei verificare ma non riesco ad accedere a https://90.147.102.74:9090/ usando chrome come suggerito

**Comment by fastluca** [comment]
@lanubile sta provando ad accedere in https, mentre deve navigare in http. Inoltre, se la pull request #88 non viene mergiata (e dunque il deploy automatico effettuato sul docker container) non può effettuare nessuna verifica perchè ci saranno ancora delle views non aggiornate.

**Comment by lanubile** [comment]
@PepponeFX mi dice che una volta effettuato l'accesso le schede si sovrappongono. Pertanto riapro l'issue

**Comment by fastluca** [comment]
@PepponeFX @lanubile è necessario aggiornare i container docker lanciando sul server il comando
`docker-compose up --build`.
Quella che vedete ora è ancora la versione precedente.
Noi possiamo farlo nel tardo pomeriggio dopo l'ufficio, se volete verificare subito invece dovete procedere voi.

**Comment by fastluca** [comment]
@PepponeFX @lanubile ho individuato altri piccoli difetti sui button che ho fixato con la pull request #91.

**Comment by PepponeFX** [comment]
@fastluca @gaetanoziri fate voi una verifica quando potete

**Comment by PepponeFX** [comment]
@fastluca @gaetanoziri 
Il menù laterale dopo il login nasconde la prima opzione sotto il titolo "Menu".
Nella pagina Evento (dove si accede per creare una sessione) le schede vanno ancora sotto il titolo della pagina. Lo stesso nella pagina Sessione (dove si accede per creare un intervento)

**Comment by fastluca** [comment]
@PepponeFX con l'ultima pull request vengono risolti tutti le issues che hai elencato nel tuo ultimo post.

**Comment by PepponeFX** [comment]
@fastluca Ancora no, cosa mi sfugge? Ho rifatto il deploy secondo il README. Allego screenshot di esempio (vale anche nelle altre pagine)
![visualbug1](https://user-images.githubusercontent.com/19552461/29818334-29bc6d16-8cbc-11e7-895d-1536b25d0469.PNG)
![visualbug2](https://user-images.githubusercontent.com/19552461/29818335-29be0e8c-8cbc-11e7-95b2-25fea3dbf25a.PNG)

**Comment by fastluca** [comment]
@PepponeFX i file sul server sono stati sostituiti (non so da chi). 
Io avevo lasciato i file contenenti le mie modifiche (che ho ripristinato ora).
Prima di sostituire i file, è necessairo portarsi le mie modifiche.
![immagine](https://user-images.githubusercontent.com/11456897/29819238-162347f8-8cc0-11e7-966e-f47cf9dad4a7.png)
![immagine](https://user-images.githubusercontent.com/11456897/29819303-62dca454-8cc0-11e7-82f9-314a54ac11a3.png)

**Comment by PepponeFX** [comment]
Perché non sono integrate nel repository?

Il 29 ago 2017 13:46, "Gianluca Colaianni" <notifications@github.com> ha
scritto:

**Comment by fastluca** [comment]
> Perché non sono integrate nel repository?
Sono sul repository, ma se non viene mergiata la pull request #96 non le trovi sul repo collab.

**Comment by PepponeFX** [comment]
Ok, non mi risultavano PR quindi pensavo fosse completo.

Il 29 ago 2017 14:12, "Gianluca Colaianni" <notifications@github.com> ha
scritto:
