### ISSUE TITLE
Ripristinare applicazione Android

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#82]
L'apk generato non è installabile su disposivi android.
è necessario riprovare con le dipendenze ripristinate (#76) e solo dopo il ripristino della visualizzazione (#81)

**Comment by gaetanoziri** [comment]
@PepponeFX di preciso che problema hai riscontrato su android?
Ho provato a generare ed installare l'apk e non ho riscontrato problemi. Ad eccezione del problema citato nella issue #81.

**Comment by PepponeFX** [comment]
@gaetanoziri con la vecchia versione di Scriba, quella nei vecchi container che è stata deployata sul server ReCaS, il file generato con il comando 'ionic build android' (anche con il tag --release) non è installabile, il file risulta danneggiato sullo smartphone

**Comment by PepponeFX** [comment]
@gaetanoziri @fastluca riuscite a generare un apk e metterlo qui nel repo?

**Comment by gaetanoziri** [comment]
@PepponeFX questo è l'apk da me generato [download apk](https://github.com/collab-uniba/scriba/files/1261831/android-debug.zip).

Questo è un apk di debug generato col comando `ionic cordova build android`.
Se vuoi generare un apk di release devi usare `ionic cordova build --release android` ma in questo caso è necessario firmare l'apk con una chiave prima di poterlo installare.

> [Ionic Publishing Guide](http://ionicframework.com/docs/v1/guide/publishing.html)

**Comment by PepponeFX** [comment]
@gaetanoziri @fastluca Ci deve essere un problema di comunicazione dell'app con il server, non riesco a ottenere gli eventi ne' a fare il login o la registrazione. Potete verificare?

**Comment by fastluca** [comment]
@PepponeFX ho appena testato con l'apk che ha fornito Gaetano e dal mio smartphone funziona senza problemi.
![screenshot_20170830-152325](https://user-images.githubusercontent.com/11456897/29875145-4890e8c4-8d99-11e7-820e-0844bbe7f1f7.jpg)
Forse hai beccato un down temporaneo del server?

**Comment by PepponeFX** [comment]
Ho riprovato adesso, funziona. Chiudo anche questa issue
