### ISSUE TITLE
Aggiungere il proxy

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/scriba#89]

**Comment by lanubile** [comment]
Una volta creato il proxy va integrato in docker-compose

**Comment by PepponeFX** [comment]
Aggiunto il sorgente e modificato il docker-compose file. @fastluca @gaetanoziri potete verificare se il compose è corretto?

**Comment by fastluca** [comment]
@PepponeFX sintatticamente sembra di sì, dobbiamo testare. Una domanda: con il proxy che accetta solo chiamate https (se non ho capito male), l'applicazione client (che comunica con il server in http) come fa a funzionare? 

_Sent from my Asus ASUS_Z017D using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by PepponeFX** [comment]
@fastluca da Chrome bisogna abilitare gli script non sicuri e funziona tutto. 
Il proxy è stato aggiunto perchè solo tramite https è possibile usare la trascrizione continua senza dover ogni volta accettare l'accesso al microfono. Se avete altre opzioni per questo proponete pure.

**Comment by fastluca** [comment]
@PepponeFX la issue #92 è relativa alle modifiche apportate per il server proxy e non permette all'applcazione di salire. Se riesci ad integrarla nel project (come bug urgent) procedo con la fix.
Grazie
