### ISSUE TITLE
spike di broadcast messaggi

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/scriba#9]
Usando web speech API di Google e Node.js

**Comment by lanubile** [comment]
dispatcher.js
Dispatcher/speakerSide.html 
Dispatcher/clientSide.html

**Comment by lanubile** [comment]
Bisogna provarlo con un microfono e mixer

**Comment by lanubile** [comment]
Il riconoscimento si interrompe dopo un certo numero parole o di tempo. E' necessario misurare per caratterizzare il problema

**Comment by flippolis** [comment]
Ho sentito @rodenic, al prossimo incontro portiamo un microfono, mixer e cavi da collegare al PC e a un impianto di amplificazione. Servirebbe quindi un aula con l'impianto per simulare un ambiente reale.

**Comment by rodenic** [comment]
Porterò anche un piccolo sistema di casse, per cui non è necessario andare in un'aula munita di amplificazione.
