### ISSUE TITLE
Ionic App not running after deploy

### ISSUE THREAD

**Issue by fastluca** [collab-uniba/scriba#92]
@PepponeFX, con la commit relativa l'inserimento del proxy per l'issue #89 hai aggiornato anche la dipendenza da ionic nel file client/package.json (3.7.0 -> 3.9.2).
Come mai?
Con la nuova versione che hai inserito, l'applicazione non sale più una volta effettuato il deploy.
Se puoi aggiungere questo issue nella user story come bug,e lo assegni a me, effettuo il rollback sul file problematico.
Grazie.

**Comment by gaetanoziri** [comment]
@fastluca  @PepponeFX  se necessario usare la versione 3.9.2 dobbiamo aggiornare il [Dockerfile di scriba](https://github.com/collab-uniba/scriba/blob/def2c5b87721f7719535c6fee716e557f4ddab4a/client/Dockerfile#L4)

**Comment by PepponeFX** [comment]
@gaetanoziri mi sembra piuttosto strano, non ho toccato nulla a parte il compose e il proxy. Comunque se non è molto costoso io andrei con l'ultima versione stabile di ionic.

**Comment by lanubile** [comment]
Per me va bene anche rimettere la dipendenza dalla versione 3.7.0 purché si chiuda velocemente.
Il problema della manutenzione adattiva si ripresenterebbe comunque a breve.

**Comment by fastluca** [comment]
@lanubile @PepponeFX ho appena testato il deploy con la versione più aggiornata e funge.
Sto effettuando le commit e la pull request.
