### ISSUE TITLE
Impossibile Avviare Intervento

### ISSUE THREAD

**Issue by PepponeFX** [collab-uniba/scriba#95]
Una volta creato Evento, Sessione, Intervento, accedendo all'Intervento per poterlo avviare viene visualizzato un messaggio di errore (allegato)
![bugintervento](https://user-images.githubusercontent.com/19552461/29815926-99c5f910-8cb2-11e7-8eb4-15b583b9a0e2.PNG)

**Comment by fastluca** [comment]
@PepponeFX puoi passare "In Progress", ci sto lavorando.
Grazie

**Comment by fastluca** [comment]
@PepponeFX con la pull request #97 si risolve questa issue.

**Comment by gaetanoziri** [comment]
@PepponeFX  questa issue possiamo ritenerla chiusa? I nostri test non hanno evidenziato altri problemi.

**Comment by PepponeFX** [comment]
Si, l'avevo chiusa da mobile ma a quanto pare non ha funzionato

Il 29 ago 2017 22:31, "Gaetano" <notifications@github.com> ha scritto:
