### ISSUE TITLE
Font inadeguati ovvero Times New Roman

### ISSUE THREAD

**Issue by lanubile** [collab-uniba/scriba#98]

**Comment by lanubile** [comment]
Vale per i pulsanti Accedi, Registrati, Esci, Nuova Sessione, ecc.

**Comment by lanubile** [comment]
@PepponeFX dice che basta cambiare il CSS

**Comment by fastluca** [comment]
@PepponeFX @lanubile quale font volete utilizzare?

**Comment by PepponeFX** [comment]
Un font che sia 'sans', va bene quello dei titoli del menù a tendina
principale

Il 01 set 2017 14:27, "Gianluca Colaianni" <notifications@github.com> ha
scritto:

**Comment by gaetanoziri** [comment]
@PepponeFX @lanubile di seguito due esempi di schermate con il font aggiornato, se mi date feedback positivo effetto la pull request.

![screen1](https://user-images.githubusercontent.com/11447382/30002692-6c6a8790-90b0-11e7-8c1e-a8b412682c53.PNG)
![screen2](https://user-images.githubusercontent.com/11447382/30002693-6c6aafb8-90b0-11e7-9819-05c06adaf85b.PNG)

**Comment by PepponeFX** [comment]
Credo che vada bene.

Il 03 set 2017 14:03, "Gaetano" <notifications@github.com> ha scritto:

**Comment by fastluca** [comment]
@PepponeFX la pull request #106 risolve questa issue.
